config/routes.rb
Rails.application.routes.draw do

  root to: "home#new"

  devise_for :users, :controllers => { :registrations => "users/registrations",:omniauth_callbacks => "users/omniauth_callbacks" , via: [:get,:post] }
 
  match 'users/:id/following' ,to: 'users#following', via:[:get]
  match 'users/:id/followers' ,to: 'users#followers', via:[:get]
 
  resources :home

  resources :relationships,       only: [:create, :destroy]

  resources :albums

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def new
		@q = User.ransack(params[:q])
	end

	def index
		@q = User.ransack(params[:q])
		@user = @q.result
	end

	def show
		@user=User.friendly.find(params[:id])



#		@album=Album.where(:user_id => @user.id,:visibility => "public")

		@album=Album.public_user_albums(@user)	

        @following =@user.following

        @follower=@user.followers


        @friend=@following & @follower


       # @friend_album=Album.where(:user_id => @user.following,:visibility => "friend")

       	@friend_album=Album.public_user_friend(@friend)
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>All users</h1>
<% if @user.count != 0 %>
	<%= @user.each do |u| %>

		 
				<%= u.username %>
		    	 <%= u.email %>
			<%= link_to 'view',home_path(u.username) %>
        		
         <br/><br/><br/>
 	<% end %>
<% else %>
	Sorry ,no such records exists
<% end %>

app/views/home/new.html.erb
<h1>Search</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= search_form_for @q , url: home_index_path do |f| %>
     
		<%= f.search_field :username_or_email_or_location_cont, placeholder: "Username Email Location",class: 'form-control' %>
  		<%= f.submit  "Search", class: "btn btn-primary" %>
    	<% end %>
    <p>New User  <%= link_to "Registation!", new_user_registration_path %></p>
  </div>
</div>

app/views/home/show.html.erb
 <% if user_signed_in? %>
  		 <%= image_tag @user.avatar ,:size => "80x80" %>
   <% end %>
   <%= @user.username %>
   <%= @user.email %>
   <%= @user.location %>
   <% if user_signed_in?  %>  		
  		<section class="stats">
            <%= render 'shared/stats' %>
 	    </section>
 	    <%= render 'shared/follow_form'  %>
           Albums List<br/><br/>

        <% if @album.count != 0 %>
		    <%= @album.each do |u| %>
			    <%= u.album_name %>
        		<%= link_to 'view',album_path(u.id) %>
			    <br/><br/><br/>
 		    <% end %>
		<% else %>
				Sorry ,no such records exists
		<% end %>
        <br/>
 friend list
 <br/><br/>

	    <% if @friend.count != 0 %>
			<%= @friend.each do |u| %>
		     	<%= u.username %>
			    <br/><br/><br/>
 	    	<% end %>
    	<% else %>
				Sorry ,no such records exists
     	<% end %>
        <br/><br/>
friend list albums(visibility =friend)
<br/><br/> 
    	<% if @friend_album.count != 0 %>
			<%= @friend_album.each do |u| %>
			    <%= u.album_name %>
        		<%= link_to 'view',album_path(u.id) %>
			    <br/><br/><br/>
 	    	<% end %>
	    <% else %>
				Sorry ,no such records exists
	    <% end %>

  <% end %>
 