config/routes.rb
Rails.application.routes.draw do

  root to: "home#new"

  devise_for :users, :controllers => { :registrations => "users/registrations",:omniauth_callbacks => "users/omniauth_callbacks" , via: [:get,:post] }
 
  match 'users/:id/following' ,to: 'users#following', via:[:get]
  match 'users/:id/followers' ,to: 'users#followers', via:[:get]
 
  resources :home

  resources :relationships,       only: [:create, :destroy]

  resources :albums

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  
  has_many :images ,dependent: :destroy

  accepts_nested_attributes_for :images,:allow_destroy => true 

  validates :user_id, presence: true
  validates :album_name, presence: true
  validates :visibility, presence: true

  def self.public_user_albums(user)
  		Album.where(:user_id => user.id,:visibility => "public")
  end

  def self.public_user_friend(user)
  		Album.where(:user_id => user,:visibility => "friend")
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	
	def index
		@album=current_user.albums.all
	end



	def new
		@album=Album.new
		@album.images.build
	
  	end
	
	def create 
		 @album = current_user.albums.build(albums_params)
	     if @album.save
    		    flash[:success] = "album created!"
      		    redirect_to albums_path    			
    	end

	end
	
	def show
		@images=Image.where(:album_id => params[:id])		
	end
	
	def destory
	
	end


  private

    def albums_params
      params.require(:album).permit(:album_name,:visibility,images_attributes: [:avatar, :_destroy])
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/index.html.erb
 <h1>All Albums</h1>
        	<%= link_to 'Add new Albums',new_album_path %>
 <br/><br/>
<% if @album.count != 0 %>
	<%= @album.each do |u| %>
		<%= u.album_name %>

        	<%= link_to 'view',album_path(u.id) %>
        
		 <br/><br/><br/>
 	<% end %>
<% else %>
	Sorry ,no such records exists
<% end %>

app/views/albums/new.html.erb
<h1>Albums </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= nested_form_for  @album ,:url => albums_path, :html => { :multipart => true }  do |f| %>
    
    <%= f.label :album_name %>
      <%= f.text_field :album_name , class: 'form-control'%>

      <%= f.label :visibility %>  
      <%= f.select :visibility, options_for_select([ "public","private","friend" ]),class: 'form-control'%>

      <%= f.fields_for :images do |u| %>
          <%= f.label "Profile" %>
          <%= u.file_field :avatar %>  
        <%= u.link_to_remove "Remove this image" %>
      <% end %>
       <p><%= f.link_to_add "Add a images", :images %></p>

      <%= f.submit "Create", class: "btn btn-primary" %>
     <% end %>
  </div>
</div>

app/views/albums/show.html.erb
<h1>All Images</h1>
        	
 <br/><br/>
<% if @images.count != 0 %>
	<%= @images.each do |a| %>

		<%= image_tag a.avatar ,:size => "80x80" %>
        
	<br/><br/>
 	<% end %>
<% else %>
	Sorry ,no such records exists
<% end %>