config/routes.rb
Rails.application.routes.draw do

  root to: "home#new"

  devise_for :users, :controllers => { :registrations => "users/registrations",:omniauth_callbacks => "users/omniauth_callbacks" , via: [:get,:post] }
 
  match 'users/:id/following' ,to: 'users#following', via:[:get]
  match 'users/:id/followers' ,to: 'users#followers', via:[:get]
 
  resources :home

  resources :relationships,       only: [:create, :destroy]

  resources :albums

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "My app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
          <li><%= link_to "Users", home_index_path %></li>
           <li><%= link_to "Albums", albums_path %></li>
         
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", home_path(current_user) %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path%></li>
        <% end %>	
      </ul>
    </nav>
  </div>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devisedemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
   <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <div class="container">
  
      <%= yield %>
      <%= render 'layouts/footer' %>

</body>
</html>